draw_config:
  # key dimensions, non-ortho layouts use key_h for width as well
  # key_w: 100 # This doesn't seem to do anything? 🤔
  key_h: 80

  # keys border radius
  key_rx: 4
  key_ry: 4

  # key labels line spacing for multi-line labels
  line_spacing: 1

  # combo box dimensions
  combo_w: 46
  combo_h: 46

  # padding from the edge of cap to top and bottom legends
  small_pad: 4

  # Padding between keys
  inner_pad_w: 1.0
  inner_pad_h: 1.0

  # padding between layers
  outer_pad_w: 0
  outer_pad_h: 0

  # gap between two halves for ortho layout generator
  # split_gap: 20 # This doesn't seem to have any effect either? 🤔

  # as it reads on the tin can, this comment is here for consistency
  append_colon_to_layer_header: false

  # shrink font size for legends wider than this many chars, set to 0 to disable
  # ideal value depends on the font size defined in svg_style and width of the boxes
  shrink_wide_legends: 5

  # Glyphs dimensions
  glyph_tap_size: 26
  glyph_hold_size: 18
  glyph_shifted_size: 18

  glyphs: {}
  glyph_urls:
    tabler: https://tabler-icons.io/static/tabler-icons/icons/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
    
  use_local_cache: true

  svg_extra_style: |
    svg.keymap {
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 18px;
      font-weight: bold;
    }
        
    text.label {
      stroke: #dfdfde;
      stroke-width: 12;
      stroke-linejoin: round;
    }
    
    rect.combo, rect.combo-separate {
      opacity: 0.95;
      stroke: #c9cccf;
      stroke-width: 0.5;
      fill: #d7eaed;
    }
    path.combo {
      stroke-dasharray: 4, 4;
      stroke-opacity: 0.3;
    } 
    
    rect.held, rect.combo.held {
      fill: #ebdada;
    }
    
    .trans.tap, .ghost.tap {
      opacity: 0.5;
    } 
    
    .shifted {
      translate: -9px 3px;
      opacity: 0.7;
    }
    
    .toggle.shifted {
      translate: -12px 17px;
      opacity: 1.0;
    }
    .toggle.hold {
      translate: 12px -25px;
    } 
    
    .text_with_symbol.tap {
      translate: -1px 1px;
    } 
    .text_with_symbol.hold {
      translate: 6px -31px;
      font-size: 8px;
    } 

parse_config:
  preprocess: true
  skip_binding_parsing: false
  mark_alternate_layer_activators: true
  zmk_remove_keycode_prefix: ["GB_"]

  trans_legend:
    tap: $$mdi:chevron-down$$
    type: trans
  raw_binding_map:

    "&tog LOCK": 
      tap: $$mdi:lock-open-outline$$
      align: top
      offset: 10
      hold: "Toggle"

    '&sys_reset': 
      tap: $$mdi:backup-restore$$
      type: bootloader
      
    '&bootloader': 
      tap: $$mdi:progress-download$$
      type: bootloader
      
    '&hml LA(LCTRL) TAB': $$mdi:keyboard-tab$$
    '&hml_repeat LS(LCTRL) 0': $$mdi:repeat$$
    
    '&hmr_lpar_lt LS(LCTRL) 0':
      tap: '('
      shifted: '<'
    '&hmr_rpar_gt LA(LCTRL) 0':
      tap: ')'
      shifted: '>'
    
    '&lbkt_lbrc':
      tap: '['
      shifted: '{'
    '&rbkt_rbrc':
      tap: ']'
      shifted: '}'
    
    '&td_sqt_dqt':
      tap: "'"
      shifted: '"'
      
    '&scw 0 RET':
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:apple-keyboard-shift$$

    '&scw LSHFT 0': $$mdi:apple-keyboard-shift$$

    '&par_macro': '( )'
    '&bkt_macro': '[]'
    '&brc_macro': '{ }'
    '&lgt_macro': '< >'

    '&kp DE_COMMA':
      tap: ','
      shifted: ';'
    
    '&kp DE_DOT':
      tap: '.'
      shifted: ':'
    
    # '&bt BT_CLR':
    #   tap: $$mdi:bluetooth$$
    #   hold: $$mdi:close-thick$$
    #   type: text_with_symbol
    '&bt BT_SEL 0':
      tap: $$mdi:bluetooth-connect$$
      hold: '1'
      shifted: ''
    '&bt BT_SEL 1':
      tap: $$mdi:bluetooth-connect$$
      hold: '2'
      shifted: ''
    '&bt BT_SEL 2':
      tap: $$mdi:bluetooth-connect$$
      hold: '3'
      shifted: ''
    # '&bt BT_SEL 3':
    #   tap: $$mdi:bluetooth-connect$$
    #   hold: '3'
    #   type: text_with_symbol
    # '&bt BT_SEL 4':
    #   tap: $$mdi:bluetooth-connect$$
    #   hold: '4'
    #   type: text_with_symbol
    # '&bt_0':
    #   tap: $$mdi:bluetooth-connect$$
    #   hold: '0'
    #   type: text_with_symbol
    # '&bt_1':
    #   tap: $$mdi:bluetooth-connect$$
    #   hold: '1'
    #   type: text_with_symbol
    # '&bt_2':
    #   tap: $$mdi:bluetooth-connect$$
    #   hold: '2'
    #   type: text_with_symbol
    # '&bt_3':
    #   tap: $$mdi:bluetooth-connect$$
    #   hold: '3'
    #   type: text_with_symbol
    # '&bt_4':
    #   tap: $$mdi:bluetooth-connect$$
    #   hold: '4'
    #   type: text_with_symbol
    # '&bt BT_DISC 0':
    #   tap: $$mdi:bluetooth-off$$
    #   hold: '0'
    #   type: text_with_symbol
    # '&bt BT_DISC 1':
    #   tap: $$mdi:bluetooth-off$$
    #   hold: '1'
    #   type: text_with_symbol
    # '&bt BT_DISC 2':
    #   tap: $$mdi:bluetooth-off$$
    #   hold: '2'
    #   type: text_with_symbol
    # '&bt BT_DISC 3':
    #   tap: $$mdi:bluetooth-off$$
    #   hold: '3'
    #   type: text_with_symbol
    # '&bt BT_DISC 4':
    #   tap: $$mdi:bluetooth-off$$
    #   hold: '4'
    #   type: text_with_symbol

    
    '&out OUT_BLE': $$mdi:bluetooth$$
    '&out OUT_USB': $$mdi:usb$$
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle
    

    # Mouse


    '&mmv MOVE_UP': M↑
    '&mmv MOVE_DOWN': M↓
    '&mmv MOVE_LEFT': M←
    '&mmv MOVE_RIGHT': M→
    '&msc SCRL_UP': MW↑
    '&msc SCRL_DOWN': MW↓
    '&msc SCRL_LEFT': MW←
    '&msc SCRL_RIGHT': MW→

    "&mkp LCLK":
      tap: $$mdi:mouse$$
      hold: L
    "&mkp RCLK":
      tap: $$mdi:mouse$$
      hold: R
    "&mkp MCLK":
      tap: $$mdi:mouse$$
      hold: M
    '&mkp MB3':
      tap: $$mdi:cursor-default-click-outline$$
      hold: 3
      type: text_with_symbol
    "&mkp MB4":
      tap: $$mdi:mouse$$
      hold: 1
    "&mkp MB5":
      tap: $$mdi:mouse$$
      hold: 2
  
  
  
  
  
  
  
  zmk_keycode_map:
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    RETURN:
      type: enter
      tap: $$mdi:keyboard-return$$
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE_CHARACTER: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    LALT: 'Alt' # UK layout
    LEFT_ALT: 'Alt' # UK layout
    RALT: 'AltGr' # UK layout
    RIGHT_ALT: 'AltGr' # UK layout
    LCTRL: 'Ctrl'
    LEFT_CONTROL: 'Ctrl'
    RCTRL: 'Ctrl'
    RIGHT_CONTROL: 'Ctrl'
    LSHFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    LGUI:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    LWIN:
      shifted: ""
      tap: $$mdi:microsoft-windows$$
      hold: ""
    LEFT_GUI:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    LMETA:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    LEFT_META:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@' # UK layout
    AT: '@' # UK layout
    HASH: '#' # UK layout
    POUND: '#' # UK layout
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: 
      tap: '-'
      shifted: '_'
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: /
      shifted: '?'

    FSLH:
      tap: /
      shifted: '?'
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: '\' # UK layout
    BSLH: '\' # UK layout
    PIPE: '|' # UK layout
    NON_US_BSLH: '\'
    NON_US_BACKSLASH: '\'
    PIPE2: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"' # UK layout
    DQT: '"' # UK layout
    COMMA:
      tap: ','
      shifted: '<'
 
    LESS_THAN: <
    LT: <
    PERIOD:
      tap: .
      shifted: '>'
    DOT:
      tap: .
      shifted: '>'
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: 
      tap: '`'
      shifted: '¬'
    TILDE: '~' # UK layout
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    N1:
      tap: 1
      shifted: '!'
    N2:
      tap: 2
      shifted: '"' # UK layout
    N3:
      tap: 3
      shifted: '£' # UK layout
    N4:
      tap: 4
      shifted: '$'
    N5:
      tap: 5
      shifted: '%'
    N6:
      tap: 6
      shifted: '^'
    N7:
      tap: 7
      shifted: '&'
    N8:
      tap: 8
      shifted: '*'
    N9:
      tap: 9
      shifted: '('
    N0:
      tap: 0
      shifted: ')'
    KP_NUM: 'Num Lock'
    KP_NUMLOCK: 'Num Lock'
    KP_MINUS: '-'
    KP_PLUS: '+'
    KP_SLASH: '/'
    KP_MULTIPLY: '*'
    KP_EQUAL: '='
    KP_DOT: '.'
    KP_N1: 1
    KP_N2: 2
    KP_N3: 3
    KP_N4: 4
    KP_N5: 5
    KP_N6: 6
    KP_N7: 7
    KP_N8: 8
    KP_N9: 9
    KP_N0: 0
    'LC(LEFT)': $$mdi:chevron-double-left$$
    'LC(RIGHT)': $$mdi:chevron-double-right$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    PAGE_UP: 'Pg Up'
    PG_UP: 'Pg Up'
    PAGE_DOWN: 'Pg Down'
    PG_DN: 'Pg Down'
    HOME: 'Home'
    END: 'End'
    PSCRN: 'Print'
    C_PP: $$mdi:play-pause$$
    C_PLAY_PAUSE: $$mdi:play-pause$$
    C_PREV: $$mdi:skip-previous$$
    C_PREVIOUS: $$mdi:skip-previous$$
    C_NEXT: $$mdi:skip-next$$
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_DOWN: $$mdi:volume-low$$
    RGB_TOG:
      tap: $$mdi:palette$$
      hold: Toggle
      type: info
    RGB_EFF:
      tap: $$mdi:palette$$
      hold: Effect
      type: info
    RGB_BRI:
      tap: $$mdi:palette$$
      hold: Brightness
      shifted: +
      type: info
    RGB_BRD:
      tap: $$mdi:palette$$
      hold: Brightness
      shifted: '-'
      type: info
    RGB_HUI:
      tap: $$mdi:palette$$
      hold: Hue
      shifted: +
      type: info
    RGB_HUD:
      tap: $$mdi:palette$$
      hold: Hue
      shifted: '-'
      type: info
    RGB_SAI:
      tap: $$mdi:palette$$
      hold: Saturation
      shifted: +
      type: info
    RGB_SAD:
      tap: $$mdi:palette$$
      hold: Saturation
      shifted: '-'
      type: info
    RGB_SPI:
      tap: $$mdi:palette$$
      hold: Speed
      shifted: +
      type: info
    RGB_SPD:
      tap: $$mdi:palette$$
      hold: Speed
      shifted: '-'
      type: info

    # Bluetooth
    BT_CLR: 
      tap: $$mdi:bluetooth$$
      hold: "clear"
    BT_SEL: $$mdi:bluetooth-connect$$
    'BT_PRV':
      shifted: ""
      tap: $$mdi:bluetooth$$
      hold: "prev"
    'BT_NXT':
      shifted: ""
      tap: $$mdi:bluetooth$$
      hold: "next"

  zmk_combos:
    caps_word:
      # align: bottom
      # offset: 1.05
      key:
        tap: 'CAPS WORD'
        shifted: ''
    tab_1:
      align: top
      offset: 0.15
      key:
        tap: $$mdi:keyboard-tab$$
        shifted: ''
    combo_bkt:
      align: top
      offset: 0.6
    combo_ger:
      align: top
      offset: 0.6