draw_config:
  # key dimensions, non-ortho layouts use key_h for width as well
  # key_w: 100 # This doesn't seem to do anything? 🤔
  key_h: 80

  # keys border radius
  key_rx: 4
  key_ry: 4

  # key labels line spacing for multi-line labels
  line_spacing: 1

  # combo box dimensions
  combo_w: 36
  combo_h: 36

  # padding from the edge of cap to top and bottom legends
  small_pad: 4

  # Padding between keys
  inner_pad_w: 1.5
  inner_pad_h: 1.5

  # padding between layers
  outer_pad_w: 0
  outer_pad_h: 0

  # gap between two halves for ortho layout generator
  # split_gap: 20 # This doesn't seem to have any effect either? 🤔

  # as it reads on the tin can, this comment is here for consistency
  append_colon_to_layer_header: false

  # shrink font size for legends wider than this many chars, set to 0 to disable
  # ideal value depends on the font size defined in svg_style and width of the boxes
  shrink_wide_legends: 5

  # Glyphs dimensions
  glyph_tap_size: 26
  glyph_hold_size: 18
  glyph_shifted_size: 18

  glyphs: {}
  glyph_urls:
    tabler: https://tabler-icons.io/static/tabler-icons/icons/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
    
  use_local_cache: true


parse_config:
  preprocess: true
  skip_binding_parsing: false
  mark_alternate_layer_activators: true
  zmk_remove_keycode_prefix: ["GB_"]
  
  trans_legend:
    tap: $$mdi:chevron-down$$
    type: trans
  raw_binding_map:
    # Custom behavior
    '&caps_word': $$mdi:apple-keyboard-caps$$
    '&smart_lshift': $$mdi:apple-keyboard-shift$$
    '&smart_rshift': $$mdi:apple-keyboard-shift$$
    '&tog 1':
      tap: $$mdi:keyboard-outline$$
      hold: Qwerty
      type: info
    '&symbols':
      tap: $$mdi:symbol$$
      hold: Symbols
      type: info
    '&tog 2':
      tap: $$mdi:symbol$$
      hold: Symbols
      type: info
    '&nav':
      tap: $$num-nav$$
      hold: Num/Nav
      type: info
    '&tog 3':
      tap: $$num-nav$$
      hold: Num/Nav
      type: info
    '&tog 4':
      tap: $$mdi:controller$$
      hold: Gaming
      type: info
    # Moergo behavior
    '&magic 5 0':
      tap: $$moergo$$
      hold: Magic
      type: info
    '&bt_0':
      type: info
      tap: $$mdi:bluetooth$$
      shifted: 0
    '&bt_1':
      type: info
      tap: $$mdi:bluetooth$$
      shifted: 1
    '&bt_2':
      type: info
      tap: $$mdi:bluetooth$$
      shifted: 2
    '&bt_3':
      type: info
      tap: $$mdi:bluetooth$$
      shifted: 3
    '&bt BT_CLR':
      type: info
      tap: $$mdi:bluetooth-off$$
      hold: Clear
    '&bt BT_CLR_ALL':
      type: info
      tap: $$mdi:bluetooth-off$$
      hold: Clr All
    '&reset': Reset
    '&sys_reset': Reset
    '&bootloader': Boot
    '&swapper': Win Next
    '&inv_qm': ¿
    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE
    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5
    '&mmv M_UP': M↑
    '&mmv M_DOWN': M↓
    '&mmv M_LEFT': M←
    '&mmv M_RIGHT': M→
    '&mwh S_UP': MW↑
    '&mwh S_DOWN': MW↓
    '&mwh S_LEFT': MW←
    '&mwh S_RIGHT': MW→
    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click
  zmk_keycode_map:
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    RETURN:
      type: enter
      tap: $$mdi:keyboard-return$$
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    LALT: 'Alt' # UK layout
    LEFT_ALT: 'Alt' # UK layout
    RALT: 'AltGr' # UK layout
    RIGHT_ALT: 'AltGr' # UK layout
    LCTRL: 'Ctrl'
    LEFT_CONTROL: 'Ctrl'
    RCTRL: 'Ctrl'
    RIGHT_CONTROL: 'Ctrl'
    LSHFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    LGUI:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    LEFT_GUI:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    LMETA:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    LEFT_META:
      tap: $$mdi:monitor-dashboard$$
      hold: Meta
      type: info
    
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '"' # UK layout
    AT: '"' # UK layout
    HASH: '£' # UK layout
    POUND: '£' # UK layout
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: '#' # UK layout
    BSLH: '#' # UK layout
    PIPE: '~' # UK layout
    NON_US_BSLH: '\'
    NON_US_BACKSLASH: '\'
    PIPE2: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '@' # UK layout
    DQT: '@' # UK layout
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '¬' # UK layout
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    N1:
      tap: 1
      shifted: '!'
    N2:
      tap: 2
      shifted: '"' # UK layout
    N3:
      tap: 3
      shifted: '£' # UK layout
    N4:
      tap: 4
      shifted: '$'
    N5:
      tap: 5
      shifted: '%'
    N6:
      tap: 6
      shifted: '^'
    N7:
      tap: 7
      shifted: '&'
    N8:
      tap: 8
      shifted: '*'
    N9:
      tap: 9
      shifted: '('
    N0:
      tap: 0
      shifted: ')'
    KP_NUM: 'Num Lock'
    KP_NUMLOCK: 'Num Lock'
    KP_MINUS: '-'
    KP_PLUS: '+'
    KP_SLASH: '/'
    KP_MULTIPLY: '*'
    KP_EQUAL: '='
    KP_DOT: '.'
    KP_N1: 1
    KP_N2: 2
    KP_N3: 3
    KP_N4: 4
    KP_N5: 5
    KP_N6: 6
    KP_N7: 7
    KP_N8: 8
    KP_N9: 9
    KP_N0: 0
    'LC(LEFT)': $$mdi:chevron-double-left$$
    'LC(RIGHT)': $$mdi:chevron-double-right$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    PAGE_UP: 'Pg Up'
    PG_UP: 'Pg Up'
    PAGE_DOWN: 'Pg Down'
    PG_DN: 'Pg Down'
    HOME: 'Home'
    END: 'End'
    PSCRN: 'Print'
    C_PP: $$mdi:play-pause$$
    C_PLAY_PAUSE: $$mdi:play-pause$$
    C_PREV: $$mdi:skip-previous$$
    C_PREVIOUS: $$mdi:skip-previous$$
    C_NEXT: $$mdi:skip-next$$
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_DOWN: $$mdi:volume-low$$
    RGB_TOG:
      tap: $$mdi:palette$$
      hold: Toggle
      type: info
    RGB_EFF:
      tap: $$mdi:palette$$
      hold: Effect
      type: info
    RGB_BRI:
      tap: $$mdi:palette$$
      hold: Brightness
      shifted: +
      type: info
    RGB_BRD:
      tap: $$mdi:palette$$
      hold: Brightness
      shifted: '-'
      type: info
    RGB_HUI:
      tap: $$mdi:palette$$
      hold: Hue
      shifted: +
      type: info
    RGB_HUD:
      tap: $$mdi:palette$$
      hold: Hue
      shifted: '-'
      type: info
    RGB_SAI:
      tap: $$mdi:palette$$
      hold: Saturation
      shifted: +
      type: info
    RGB_SAD:
      tap: $$mdi:palette$$
      hold: Saturation
      shifted: '-'
      type: info
    RGB_SPI:
      tap: $$mdi:palette$$
      hold: Speed
      shifted: +
      type: info
    RGB_SPD:
      tap: $$mdi:palette$$
      hold: Speed
      shifted: '-'
      type: info

