manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
#    - name: zmk
 #      remote: caksoylar
 #     revision: caksoylar/zen-8bit
 #     # revision: caksoylar/zen-v1+v2+experimental
 #   import: app/west.yml
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-smart-toggle
      remote: caksoylar
      revision: main
  self:
    path: config
# manifest:
#   remotes:
#     - name: morou
#       url-base: https://github.com/morou
#   projects:
#     - name: zmk
#       remote: morou
#       revision: zen-v1+v2-debug
#       import: app/west.yml
#   self:
#     path: config

